#!/bin/bash

echo "Good afternoon  sweet Refia"

Sleep 3

echo "Pearls grow deep in the sea."

Sleep 3

echo "Friends are precious pearls."

sleep 3

echo "I always grow them with lots of love"

Sleep 3

echo "with my soul and heart"

Sleep 3

echo "You  are my precious pearl my sweet and kind Refia"

Sleep 3

echo "Love you <3"

